# Generated by Django 5.1 on 2024-08-31 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='books.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('w', 'Wish'), ('t', 'To read'), ('r', 'Reserved'), ('l', 'Loaned'), ('s', 'Sold'), ('n', 'Not found')], default='a', max_length=1),
        ),
        migrations.DeleteModel(
            name='Rating1',
        ),
    ]
