# Generated by Django 5.1 on 2024-08-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_status_status_book_alter_status_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('a', 'Available'), ('w', 'Wish'), ('t', 'To read'), ('r', 'Reserved'), ('l', 'Loaned'), ('s', 'Sold'), ('n', 'Not found'), ('d', 'Not found')], default='a', max_length=1),
        ),
    ]
