# Generated by Django 5.1 on 2024-08-31 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_status_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('w', 'Wish'), ('t', 'To read'), ('a', 'Available'), ('r', 'Reserved'), ('l', 'Loaned'), ('f', 'For sale'), ('s', 'Sold'), ('n', 'Not found')], default='a', max_length=1),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'book'], name='books_ratin_user_id_ca2f72_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['user', 'book'], name='books_statu_user_id_0adba6_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_rating_per_user'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_status_per_user'),
        ),
    ]
