# Generated by Django 5.1 on 2024-09-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_rating_options_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('w', 'Wish'), ('t', 'To read'), ('a', 'Available'), ('r', 'Reserved'), ('l', 'Loaned'), ('f', 'For sale'), ('s', 'Sold'), ('n', 'Not found')], default='a', max_length=1, verbose_name='Status'),
        ),
    ]
