# Generated by Django 5.0.6 on 2024-06-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_author'),
    ]

    operations = [
    ]
