# Generated by Django 5.1 on 2024-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_source',
            field=models.CharField(choices=[('p', 'Purchase'), ('r', 'Reference')], default='p', max_length=1, verbose_name='Price source'),
        ),
    ]
