# Generated by Django 5.0.6 on 2024-06-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_uploadedfile_book_created_by_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
    ]
