# Generated by Django 5.1 on 2024-09-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_volume_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='book',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='books.collection', verbose_name='Collection'),
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
