# Generated by Django 5.0.6 on 2024-06-27 22:03

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_uploadedfile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copyright',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book.png', upload_to=apps.books.models.upload_to_books),
        ),
    ]
