# Generated by Django 5.0.6 on 2024-06-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_copyright_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(null=True),
        ),
    ]
