# Generated by Django 5.0.6 on 2024-06-28 21:17

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_copyright_alter_book_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book.png', null=True, upload_to=apps.books.models.upload_to_books),
        ),
    ]
