# Generated by Django 5.0.6 on 2024-06-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_author_created_by_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
