# Generated by Django 5.0.6 on 2024-06-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_remove_book_category_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Title...', max_length=255),
        ),
    ]
