# Generated by Django 5.0.6 on 2024-06-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_alter_book_edition_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
