# Generated by Django 5.0.6 on 2024-06-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(upload_to='author'),
        ),
    ]
