# Generated by Django 5.0.6 on 2024-06-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_alter_author_headshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='headshot',
        ),
    ]
