# Generated by Django 5.0.6 on 2024-06-30 20:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_author_headshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, Romance etc.)', max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('f', 'fiction'), ('n', 'non-fiction'), ('c', "children's")], default='f', help_text='Book category', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='genre_unique', violation_error_message='Genre already exists'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='books.genre'),
        ),
    ]
