# Generated by Django 5.0.6 on 2024-07-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0042_alter_rating_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('f', 'Fiction'), ('n', 'Non-fiction'), ('c', "Children's")], default='f', help_text='Book category', max_length=1),
        ),
    ]
