# Generated by Django 5.0.6 on 2024-08-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0047_rating_book_rating_status_book_stutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='stutus',
            new_name='status',
        ),
    ]
