# Generated by Django 5.0.6 on 2024-08-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0048_rename_stutus_book_status'),
    ]

    operations = [
    ]
