# Generated by Django 5.0.6 on 2024-08-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0049_auto_20240805_2005'),
    ]

    operations = [
    ]
