# Generated by Django 5.1 on 2024-09-04 21:21

import apps.books.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to='avantars/', validators=[apps.books.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), apps.books.validators.validate_image], verbose_name='Avatar'),
        ),
    ]
